zabbix_cli.auth][None][WARNING][auth.py:116 login]: Failed to log in with _get_username_password_config: ('Failed to log out of Zabbix API: %s', ZabbixAPIRequestError('Error: Invalid request.: Invalid parameter "/": unexpected parameter "auth".')): (-32600) Invalid request. Invalid parameter "/": unexpected parameter "auth".
